//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACMEntities : DbContext
    {
        public ACMEntities()
            : base("name=ACMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AuditEntry> AuditEntries { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<EmailTo> EmailToes { get; set; }
        public virtual DbSet<OFI> OFIs { get; set; }
        public virtual DbSet<OFIAssigned> OFIAssigneds { get; set; }
        public virtual DbSet<OFICategory> OFICategories { get; set; }
        public virtual DbSet<OFIEntry> OFIEntries { get; set; }
        public virtual DbSet<OFIFile> OFIFiles { get; set; }
        public virtual DbSet<OFIOrigin> OFIOrigins { get; set; }
        public virtual DbSet<OFIType> OFITypes { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<ReportCategory> ReportCategories { get; set; }
        public virtual DbSet<ReportFile> ReportFiles { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<OFIDueDate> OFIDueDates { get; set; }
    }
}
