//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFI
    {
        public int OFIID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public int OFICategoryID { get; set; }
        public int OFIOriginID { get; set; }
        public int OFITypeID { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public int PriorityID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<double> TimeEstimation { get; set; }
        public int StatusID { get; set; }
        public string LockUserID { get; set; }
        public Nullable<System.DateTime> LockDateTime { get; set; }
        public string ApprovedUserID { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
    }
}
