//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFICategory
    {
        public int OFICategoryID { get; set; }
        public string OFICategoryCode { get; set; }
        public string OFICategoryName { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
    }
}
