//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFIDueDate
    {
        public int OFIDueDateID { get; set; }
        public int OFIID { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime DueDateCreatedDate { get; set; }
        public string DueDateCreatedID { get; set; }
    }
}
