//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public int ReportCategoryID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string ReviewUserID { get; set; }
        public Nullable<System.DateTime> ReviewDateTime { get; set; }
        public string Comments { get; set; }
        public string AuditUserID { get; set; }
        public string AuditDateTime { get; set; }
        public string AuditComments { get; set; }
        public Nullable<int> ReportFileID { get; set; }
    }
}
