//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportFile
    {
        public int ReportFileID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ContentType { get; set; }
        public long FileLength { get; set; }
        public string FullFileName { get; set; }
        public string FileDescription { get; set; }
    }
}
