//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public string HexColour { get; set; }
        public bool Deleted { get; set; }
    }
}
