//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditEntry
    {
        public int AuditEntryID { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public string UserID { get; set; }
        public Nullable<int> OFIID { get; set; }
        public string AuditEntryType { get; set; }
        public string Description { get; set; }
    }
}
